# Generated by Django 5.0.4 on 2024-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='الكلمة')),
                ('meaning', models.CharField(max_length=255, verbose_name='المعنى')),
            ],
            options={
                'verbose_name': 'كلمة',
                'verbose_name_plural': 'الكلمات',
            },
        ),
    ]
